server:
  port: 80
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/oauth/token
      user-authorization-uri: http://localhost:${server.port}/oauth/authorize
      client-id: web
    resource:
      user-info-uri: http://localhost:${server.port}/api2/member
      prefer-token-info: false